// <auto-generated />
using System;
using GMMWSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMMWSystem.Migrations
{
    [DbContext(typeof(GMMWDBContext))]
    partial class GMMWDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("GMMWSystem.Booking", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("bookedVehicleID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("bookedVehicleID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GMMWSystem.Motorist", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Motorists");
                });

            modelBuilder.Entity("GMMWSystem.Part", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepairID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RepairID");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("GMMWSystem.Repair", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartsCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ascBookingID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ascBookingID");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("GMMWSystem.Student", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepairID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RepairID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("GMMWSystem.Vehicle", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("engine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("transmission")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GMMWSystem.Booking", b =>
                {
                    b.HasOne("GMMWSystem.Vehicle", "bookedVehicle")
                        .WithMany()
                        .HasForeignKey("bookedVehicleID");

                    b.Navigation("bookedVehicle");
                });

            modelBuilder.Entity("GMMWSystem.Part", b =>
                {
                    b.HasOne("GMMWSystem.Repair", null)
                        .WithMany("parts")
                        .HasForeignKey("RepairID");
                });

            modelBuilder.Entity("GMMWSystem.Repair", b =>
                {
                    b.HasOne("GMMWSystem.Booking", "ascBooking")
                        .WithMany("Repairs")
                        .HasForeignKey("ascBookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ascBooking");
                });

            modelBuilder.Entity("GMMWSystem.Student", b =>
                {
                    b.HasOne("GMMWSystem.Repair", null)
                        .WithMany("repairers")
                        .HasForeignKey("RepairID");
                });

            modelBuilder.Entity("GMMWSystem.Vehicle", b =>
                {
                    b.HasOne("GMMWSystem.Motorist", "owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("GMMWSystem.Booking", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("GMMWSystem.Repair", b =>
                {
                    b.Navigation("parts");

                    b.Navigation("repairers");
                });
#pragma warning restore 612, 618
        }
    }
}
